<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ViabilityIQ.Database\ViabilityIQ.Application.csproj" />
    <ProjectReference Include="..\ViabilityIQ.Shared\ViabilityIQ.Shared.csproj" />
  </ItemGroup>

</Project>
