namespace ViabilityIQ.Shared.SharedModels;

public enum ActivityEntityType
{
    User,
    Admin,
    Guest,
    Assessment,
    Business,
    Client,
    Asset,
    AssetMovement,
    Loan,
    LoanType,
    Expense,
    ExpenseType,
    Revenue,
    IncomeType,
    Stock,
    FinancialStatement,
    Report,
    Scenario,
    Assumption,
    Document,
    Debtor,
    Creditor,
    Transaction,
    Payment,
    Bank,
    Branch,
    Province,
    Company,
    BusinessSector,
    Product,
    ProductCategory,
    Notification
}
