using Dapper.Contrib.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ViabilityIQ.Shared.DataModelsInterfaces;

namespace ViabilityIQ.Shared.DataModels
{

    [Table("tblActivityLog")]
    public class ActivityLog: IEntity, IAuditableEntity, ISortableEntity
    {
        [Key] public long ActivityLogId { get; set; }

        // Who
        public long? UserId { get; set; }
        public string? ActorName { get; set; }

        // What happened
        public string ActivityType { get; set; } = string.Empty;
        public string ActivityAction { get; set; } = string.Empty;

        // What was affected
        public string EntityType { get; set; } = string.Empty;
        public long? EntityId { get; set; }
        public string? EntityName { get; set; }

        // Business context
        public long? AssessmentId { get; set; }
        public string? AssessmentName { get; set; }

         // Technical context
        public string? Module { get; set; }
        public string? Page { get; set; }

        // Request/session context
        public string? IpAddress { get; set; }
        public string? UserAgent { get; set; }
        public string? CorrelationId { get; set; }

        // Optional data
        public string? MetadataJson { get; set; }

        // Human-readable description
        public string? Remarks { get; set; }
        public bool Active { get; set; }
        public DateTime CreatedDate { get; set; } = DateTime.UtcNow;
        public long CreatedBy { get; set; }
        public DateTime ModifiedDate { get; set; } = DateTime.UtcNow;
        public long ModifiedBy { get; set; }

        long IEntity.Id => ActivityLogId;
        string ISortableEntity.DisplayName => Remarks;       //Generated by the system


    }
}
