using Dapper.Contrib.Extensions;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ViabilityIQ.Shared.DataModelsInterfaces;


namespace ViabilityIQ.Shared.DataModels
{
    [Dapper.Contrib.Extensions.Table("tblAssessmentExpenses")]
    public class AssessmentExpenses : IEntity, IAuditableEntity, ISortableEntity
    {
        [Key] public long AssessmentExpenseId { get; set; }
        public long AssessmentId { get; set; }
        public long ExpenseItemId { get; set; }
        public long ExpenseTypeId { get; set; }
        public string? Description { get; set; }
        public bool blSendToCashBook { get; set; }
        public bool blSameMonthlyAmountUsed {get;set;}
        public decimal SameMonthlyAmount { get; set; }       
	    public bool blPercentageOfSalesUsed { get; set; }
	    public decimal PercentageOfSalesRate { get; set; }               
        public decimal Month_1 { get; set; }
        public decimal Month_2 { get; set; }
        public decimal Month_3 { get; set; }
        public decimal Month_4 { get; set; }
        public decimal Month_5 { get; set; }
        public decimal Month_6 { get; set; }
        public decimal Month_7 { get; set; }
        public decimal Month_8 { get; set; }
        public decimal Month_9 { get; set; }
        public decimal Month_10 { get; set; }
        public decimal Month_11 { get; set; }
        public decimal Month_12 { get; set; }
        public decimal TotalNoVAT { get; set; }
        public decimal TotalWithVAT { get; set; }
        public bool Active { get; set; }
        public string? Remarks { get; set; }
        public DateTime CreatedDate { get; set; }= DateTime.UtcNow;
        public long CreatedBy { get; set; }
        public DateTime ModifiedDate { get; set; } = DateTime.UtcNow;
        public long ModifiedBy { get; set; }

        [Write(false)] public decimal [] MonthlyValues
        {
            get => new decimal[] { Month_1, Month_2, Month_3, Month_4, Month_5, Month_6, Month_7, Month_8, Month_9, Month_10, Month_11, Month_12 };
            set
            {
                if (value.Length == 12)
                {
                    Month_1 = value[0]; Month_2 = value[1]; Month_3 = value[2]; Month_4 = value[3];
                    Month_5 = value[4]; Month_6 = value[5]; Month_7 = value[6]; Month_8 = value[7];
                    Month_9 = value[8]; Month_10 = value[9]; Month_11 = value[10]; Month_12 = value[11];
                }
                else
                {
                    throw new ArgumentException("MonthlyValues array must have exactly 12 elements.");
                }
            }
        } 
        [Write(false)] public decimal Month { get; set; }


        long IEntity.Id => AssessmentExpenseId;
        string ISortableEntity.DisplayName => Remarks;       //Generated by the system

        public void ForceSync()
        {
            // This explicitly runs the mapping logic
            var temp = MonthlyValues;
            MonthlyValues = temp;
        }
    }
}
