using Dapper.Contrib.Extensions;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Linq;
using System.Runtime.Intrinsics.X86;
using System.Text;
using System.Threading.Tasks;
using ViabilityIQ.Shared.DataModelsInterfaces;
using ViabilityIQ.Shared.SharedModels;

namespace ViabilityIQ.Shared.DataModels
{

    [Table("tblAssessments")]
    public class Assessment : IEntity, IAuditableEntity, ISortableEntity
    {
        [Dapper.Contrib.Extensions.Key] public long AssessmentId { get; set; }
        [Computed] public string? CaseNumber { get; set; }

        [Required(ErrorMessage ="Assessment type is required")]
        public long AssessmentTypeId { get; set; }      //Either Cash Business OR Credit Business; Cash Business does not have Debtors/creditors        

        [Required(ErrorMessage ="Business being assessed must be specified.")]
        public long BusinessId { get; set; }

        [Required(ErrorMessage ="Specify starting date")]
        public DateTime? AssessmentStartDate { get; set; } = DateTime.UtcNow;
        public DateTime? AssessmentFinishDate { get; set; } = DateTime.UtcNow.AddDays(25); //Assessment is expected to take 3 working weeks


        //VAT SECTION
        public long VATRate { get; set; }        //Universal VAT rate for the assessment

        //OPENING BALANCES SECTION
        public decimal OpeningBalance_Assets { get; set; }
        public decimal OpeningBalance_Bank { get; set; }        
        public decimal InterestOnOverDraft { get; set; } = 0;
        public decimal DepreciationProjectedAmount { get; set; } = 0;       

        //DIRECTORS WAGES SECTION
        public decimal MonthlyDirectorWagesAmountTotal { get; set; }
        public decimal MonthlyDirectorWagesAmount { get; set; }
        public int NumberOfDirectors { get; set; }  
        public long StatusId { get; set; }
        public long ProgressPercentage { get; set; }
        public long blStock { get; set; }
        public long blDebtorsCreditors { get; set; }
        public long blExpenses { get; set; }
        public long blSales { get; set; }
        public long blVat { get; set; }
        public string? Remarks { get; set; }
        public bool Active { get; set; }
        public DateTime CreatedDate { get; set; } = DateTime.UtcNow;
        public long CreatedBy { get; set; }
        public DateTime ModifiedDate { get; set; } = DateTime.UtcNow;
        public long ModifiedBy { get; set; }

        long IEntity.Id => AssessmentId;
        string ISortableEntity.DisplayName => CaseNumber;       //Generated by the system
    }
}
